### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by makatsis** [Daniel-KM/Omeka-S-module-UserProfile#1]
After I installed the latest version of the User Profile at the omeka-s version 3.0.1 , I got the following error. 

Fatal error: Declaration of UserProfile\Module::handleUserSettings(Laminas\EventManager\Event $event): void must be compatible with Generic\AbstractModule::handleUserSettings(Laminas\EventManager\Event $event): ?Laminas\Form\Fieldset in /var/www/html/omeka/modules/UserProfile/Module.php on line 105

**Comment by Daniel-KM** [comment]
You should upgrade module Generic first if you installed it. If not, I just published an update of this module to fix it.
